server:
  port: 1688

spring:
  config:
    import: optional:file:/vault/secrets/db-config.properties

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:lottery}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  
  data:
    redis:
      sentinel:
        master: mymaster
        nodes: ${REDIS_HOST:localhost}:26379

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: lotto-group
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.my-app-sit.svc.cluster.local:30443/realms/lotto-realm

mybatis:
  type-aliases-package: com.nlnl.lotto.domain