server:
  port: 1688

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:lottery}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: lotto-group
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8080/realms/lotto-realm